Catch wallet abort connection error
baking-bad/bcd pull request #551
Opened 2023-08-04 22:58 UTC by GusevPM

2023-08-04 23:02 UTC, GusevPM commented
@aopoltorzhicky Так и не смог понять где происходит (и соответственно обработать) ошибку, которая появляется, если два раза подряд повторить отменить подключение кошелька уже после выбора Темпла.

2023-08-05 10:57 UTC, aopoltorzhicky approved these changes

2023-08-05 14:54 UTC, aopoltorzhicky requested changes

2023-08-05 14:54 UTC, aopoltorzhicky commented on src/utils/wallet.js
> +                if (e.title.toUpperCase() === 'ABORTED') {
Нужно добавить проверку на существование e.title. В общем случае, этого поля может не быть и свалится тогда в новый необработанный эксепшн.

2023-08-05 17:00 UTC, aopoltorzhicky approved these changes

2023-08-06 15:26 UTC, merged